//tipe data number (berupa angka)
document.writeln(1)
document.writeln(2)
document.writeln(3)
document.writeln("<br></br>")
//tipe data bolean (terdiri dari 2 statment yaitu benar (true) dan salah(false))
document.writeln(true)
document.writeln(false)
document.writeln("<br></br>")
//tipe data string (Berupa kalimat / huruf)
document.writeln('ini merupakan tipe data string')